name: chatapp
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

flutter_native_splash:
  color: "#3363FF"
  image: assets/splashscreen.png
  android: true
  ios: true

